name: tests

on:
  push:
    branches: [develop, qa, main]
  pull_request:
    branches: [develop, qa, main]

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: k2-arc-linux
    timeout-minutes: 20
    env:
      npm_config_cache: ~/.npm
    steps:
      - uses: actions/checkout@v4
      - run: node -v && npm -v
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
